Feature/gcn email
LCOGT/hermes pull request #45
Opened 2023-05-03 23:07 UTC by jnation3406

2023-05-09 17:06 UTC, jchate6 commented
closes #28

2023-05-09 18:25 UTC, phycodurus requested changes
@cmccully I'm happy to make these changes if you want me to. Just let me know.

2023-05-09 18:25 UTC, phycodurus commented on helm-chart/values-dev.yaml
> +hermesEmail: hermes@lco.global
I know the email have to be secret, but for consistency's sake I have `HERMES_EMAIL_USERNAME` and `HEREMS_EMAIL_PASSWORD` defined as k8s secrets (in both dev and prod namespaces). I think keeping these values together and handling them consistently reduces cognitive complexity.

2023-05-09 18:25 UTC, phycodurus commented on helm-chart/templates/_helpers.tpl
> +- name: HERMES_EMAIL
Please handle in a way consistent with `HERMES_EMAIL_PASSWORD` (see other comments)

2023-05-09 18:25 UTC, phycodurus commented on hermes/views.py
> +    send_email(settings.GCN_EMAIL, settings.HERMES_EMAIL, settings.HERMES_EMAIL_PASSWORD,
I know the email have to be secret, but for consistency's sake I have `HERMES_EMAIL_USERNAME` and `HEREMS_EMAIL_PASSWORD` defined as k8s secrets. I think keeping these values together and handling them consistently reduces cognitive complexity.

2023-05-09 18:25 UTC, phycodurus commented on hermes_base/settings.py
> +HERMES_EMAIL = os.getenv('HERMES_EMAIL', 'hermes@lco.global')
Please treat these consistently (see other comments).

2023-05-10 22:58 UTC, phycodurus approved these changes

2023-05-10 22:59 UTC, merged